plugin: aws_ec2

#aws_access_key: 
#aws_secret_key: 

regions:
  - ap-south-1b

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - 172.31.7.128

compose:
  ansible_host: 172.31.7.128
